package com.umd.pothole.hibernate;
// Generated Mar 18, 2014 12:41:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device  implements java.io.Serializable {


     private String androidid;
     private Date registered;
     private Set reports = new HashSet(0);

    public Device() {
    }

	
    public Device(String androidid, Date registered) {
        this.androidid = androidid;
        this.registered = registered;
    }
    public Device(String androidid, Date registered, Set reports) {
       this.androidid = androidid;
       this.registered = registered;
       this.reports = reports;
    }
   
    public String getAndroidid() {
        return this.androidid;
    }
    
    public void setAndroidid(String androidid) {
        this.androidid = androidid;
    }
    public Date getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(Date registered) {
        this.registered = registered;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }




}


